services:
  steam-monitor:
    build:
      context: .
    image: steam-monitor-js:latest
    container_name: steam_monitor
    restart: unless-stopped
    init: true
    env_file:
      - .env
    environment:
      PORT: "5555"
      SQLITE_DB_PATH: /app/data/friend_game_history.db
    ports:
      - "127.0.0.1:5555:5555"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
